apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    secureJsonData:
      token: $INFLUXDB_TOKEN
    jsonData:
      version: Flux
      organization: mtc
      defaultBucket: mtcbucket
  - name: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    uid: postgres-ds
    editable: true
    user: $POSTGRES_USER
    database: $POSTGRES_DB
    jsonData:
      postgresVersion: 1300
      sslmode: 'disable'
    secureJsonData:
      password: $POSTGRES_PASSWORD
